[workspace]
resolver = "2"
members = [ "cargo-edit-issue-891" ]

[workspace.package]
version = "0.1.0"
authors = [ "Michael Brogdon <Michael.Brogdon@monotype.com>" ]
description = "A workspace for reproducing cargo-edit issue 891"
edition = "2021"
