name: "Generate release tag and PR for version update"

on:
  push:
    branches:
      - "main"

jobs:

  # Update the rust workspace version (if it hasn't yet been updated), or if it
  # has been updated, created a tag to reflect the new workspace version.
  version-update:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Update version
        uses: "./.github/actions/version-update"
        with:
          version: "0.2.0"
